try:
    from humming._version import version as __version__  # generated by setuptools_scm at build time
except ImportError:  # not built/installed (e.g. running from a source tree without a build)
    try:
        from importlib.metadata import version as _pkg_version

        __version__ = _pkg_version("humming-kernels")
    except Exception:
        __version__ = "0.0.0+unknown"

import humming.ops  # noqa
import humming.dtypes  # noqa
